import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f9f9f9',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#454652',
        'on-background': '#1a1c1c',
        primary: '#000666',
        'primary-container': '#1a237e',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#8690ee',
        'on-primary-fixed': '#000767',
        'on-primary-fixed-variant': '#343d96',
        secondary: '#1b6d24',
        'secondary-container': '#a0f399',
        'secondary-fixed': '#a3f69c',
        'secondary-fixed-dim': '#88d982',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#217128',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005312',
        tertiary: '#380b00',
        'tertiary-container': '#5c1800',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#e17c5a',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#7b2e12',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#767683',
        'outline-variant': '#c6c5d4',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'inverse-primary': '#bdc2ff',
        'surface-tint': '#4c56af',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Work Sans', 'Assistant', 'sans-serif'],
        body: ['Inter', 'Assistant', 'sans-serif'],
        label: ['Inter', 'Assistant', 'sans-serif'],
      },
      boxShadow: {
        editorial: '0 24px 40px rgba(26, 35, 126, 0.05)',
        'editorial-sm': '0 4px 24px rgba(26, 35, 126, 0.05)',
        'editorial-btn': '0 8px 20px rgba(26, 35, 126, 0.15)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};

export default config;
